<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'reports.view',
            'reports.create',
            'reports.update.returned',
            'reports.transition',
            'reports.export.personal',
            'reports.export.department',
            'reports.export.branch',
            'notifications.view',
            'messages.view',
            'messages.create',
            'messages.reply',
            'formal_correspondences.view',
            'formal_correspondences.create',
            'formal_correspondences.route',
            'formal_correspondences.delete',
            'circulars.view',
            'circulars.create',
            'offices.manage',
            'roles.permissions.manage',
            'tasks.create',
            'tasks.update',
            'tasks.delete_with_activities',
            'tasks.review',
            'tasks.statistics.view',
            'organization.view',
            'organization.tree.manage',
            'branches.create',
            'branches.update',
            'branches.delete',
            'departments.create',
            'departments.update',
            'departments.delete',
            'employees.view',
            'employees.create',
            'employees.update',
            'employees.delete',
            'database.backups.manage',
            'database.maintenance.manage',
            'forms.view',
            'forms.publish',
            'forms.submissions.view',
            'forms.export',
            'forms.manage',
            'hr.view',
            'hr.manage',
            'hr.request',
            'hr.approve',
            'fleet.view',
            'fleet.manage',
            'fleet.request',
            'fleet.approve',
            'templates.manage',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        $roles = [
            'employee' => [
                'hr.request',
                'fleet.request',
                'reports.view',
                'reports.create',
                'reports.update.returned',
                'reports.transition',
                'reports.export.personal',
                'notifications.view',
                'messages.view',
                'messages.create',
                'messages.reply',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'circulars.view',
                'forms.view',
                'forms.submissions.view',
            ],
            'technician' => [
                'hr.request',
                'fleet.request',
                'reports.view',
                'reports.create',
                'reports.update.returned',
                'reports.transition',
                'reports.export.personal',
                'notifications.view',
                'messages.view',
                'messages.create',
                'messages.reply',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'circulars.view',
                'forms.view',
                'forms.submissions.view',
            ],
            'department_head' => [
                'hr.request',
                'fleet.request',
                'tasks.create',
                'tasks.update',
                'tasks.delete_with_activities',
                'tasks.review',
                'tasks.statistics.view',
                'reports.view',
                'reports.transition',
                'reports.export.department',
                'notifications.view',
                'messages.view',
                'messages.create',
                'messages.reply',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'circulars.view',
                'circulars.create',
                'organization.view',
                'employees.view',
                'employees.update',
                'forms.view',
                'forms.publish',
                'forms.submissions.view',
                'forms.export',
            ],
            'branch_manager' => [
                'hr.request',
                'fleet.request',
                'tasks.create',
                'tasks.update',
                'tasks.delete_with_activities',
                'tasks.review',
                'tasks.statistics.view',
                'reports.view',
                'reports.transition',
                'reports.export.branch',
                'notifications.view',
                'messages.view',
                'messages.create',
                'messages.reply',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'circulars.view',
                'circulars.create',
                'organization.view',
                'departments.create',
                'departments.update',
                'departments.delete',
                'employees.view',
                'employees.create',
                'employees.update',
                'employees.delete',
                'forms.view',
                'forms.publish',
                'forms.submissions.view',
                'forms.export',
            ],
            'general_manager' => [
                'hr.view',
                'hr.request',
                'fleet.view',
                'fleet.request',
                'tasks.create',
                'tasks.update',
                'tasks.delete_with_activities',
                'tasks.review',
                'tasks.statistics.view',
                'reports.view',
                'reports.transition',
                'reports.export.branch',
                'notifications.view',
                'messages.view',
                'messages.create',
                'messages.reply',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'formal_correspondences.delete',
                'circulars.view',
                'circulars.create',
                'offices.manage',
                'organization.view',
                'branches.create',
                'branches.update',
                'branches.delete',
                'departments.create',
                'departments.update',
                'departments.delete',
                'employees.view',
                'employees.create',
                'employees.update',
                'employees.delete',
                'forms.view',
                'forms.publish',
                'forms.submissions.view',
                'forms.export',
            ],
            'database_manager' => [
                'hr.request',
                'fleet.request',
                'tasks.create',
                'tasks.update',
                'tasks.delete_with_activities',
                'tasks.review',
                'tasks.statistics.view',
                'reports.view',
                'reports.update.returned',
                'reports.transition',
                'reports.export.branch',
                'database.backups.manage',
                'database.maintenance.manage',
                'templates.manage',
                'forms.manage',
                'forms.view',
                'forms.publish',
                'forms.submissions.view',
                'forms.export',
                'roles.permissions.manage',
                'formal_correspondences.view',
                'formal_correspondences.create',
                'formal_correspondences.route',
                'offices.manage',
                'organization.view',
                'organization.tree.manage',
                'branches.create',
                'branches.update',
                'branches.delete',
                'departments.create',
                'departments.update',
                'departments.delete',
                'employees.view',
                'employees.create',
                'employees.update',
                'employees.delete',
            ],
        ];

        foreach ($roles as $name => $rolePermissions) {
            Role::firstOrCreate(['name' => $name, 'guard_name' => 'web'])->syncPermissions($rolePermissions);
        }

        Permission::whereIn('name', ['project_master.view', 'project_master.manage'])->delete();
    }
}
